package net.hypixel.nerdbot.command;

import com.freya02.botcommands.api.application.ApplicationCommand;
import com.freya02.botcommands.api.application.slash.GuildSlashEvent;
import com.freya02.botcommands.api.application.slash.annotations.JDASlashCommand;

public class FactCommands extends ApplicationCommand {

    private static final String[] FACTS = {
        "Horses can sleep both lying down and standing up, thanks to a special \"stay apparatus\" in their legs.",
        "A horse's teeth can tell its age. As they age, their teeth change shape and develop wear patterns.",
        "Horses have the largest eyes of any land mammal.",
        "A horse's heart weighs approximately 10 pounds and beats at a rate of around 30 beats per minute.",
        "The fastest recorded speed of a horse was over 55 miles per hour.",
        "Horses have a strong memory and can remember complex routes and locations for years.",
        "The ancient Greeks believed that horses were created by Poseidon, the god of the sea.",
        "A foal (baby horse) can stand and walk shortly after birth.",
        "The tallest horse ever recorded was a Shire named Sampson, who stood at 21.2 hands (7 feet 2 inches) tall.",
        "Horses have a unique digestive system that relies on fermentation in their large intestine.",
        "Horses can see nearly 360 degrees around them because their eyes are located on the sides of their heads.",
        "The Przewalski's horse is the only truly wild horse species left in the world.",
        "Horses use their ears, eyes, and nostrils to communicate their mood and intentions.",
        "The term \"hands\" is used to measure a horse's height and equals four inches.",
        "A horse's hoof is made from the same protein as human hair and fingernails.",
        "Horses have a special adaptation called the \"flehmen response\" where they curl their upper lip to better detect scents.",
        "Horses are herbivores, meaning they only eat plants.",
        "Horses have a natural hierarchy within their herds, with a lead mare often leading the group.",
        "A horse's hoof grows continuously and requires regular trimming and shoeing.",
        "The Akhal-Teke is a horse breed known for its metallic sheen on its coat, giving it a unique appearance.",
        "Horses have a strong flight response, meaning they are easily startled by sudden movements or loud noises.",
        "The Friesian horse breed is known for its luxurious mane and tail.",
        "Horses have around 205 bones in their skeleton.",
        "The Andalusian horse breed is famous for its elegant movements and noble appearance.",
        "Horses can communicate with each other through vocalizations, body language, and facial expressions.",
        "Arabian horses are one of the oldest horse breeds in the world, dating back thousands of years.",
        "Horses have a blind spot directly in front of and behind them.",
        "The Mustang is a wild horse that descended from horses brought to the Americas by Spanish explorers.",
        "Horses have a strong sense of balance, allowing them to navigate various terrains with ease.",
        "Icelandic horses have a unique gait called the \"tölt,\" which is smooth and comfortable for riders.",
        "Horses have a strong sense of herd mentality and often form close bonds with other horses.",
        "The Clydesdale horse breed is known for its strength and distinctive feathering on its lower legs.",
        "Horses can live for up to 25 to 30 years, depending on factors like breed and care.",
        "The Lipizzaner horse breed is famous for its performances in classical dressage.",
        "Horses have a natural instinct to roll in dust or mud to help keep their coat clean and free from parasites.",
        "The Appaloosa horse breed is known for its spotted coat pattern.",
        "Horses have been used in warfare throughout history, providing transportation and carrying soldiers into battle.",
        "The Tennessee Walking Horse is known for its smooth, gliding gait called the \"running walk.\"",
        "Horses have a complex social structure within their herds, with dominant and submissive roles.",
        "The American Quarter Horse is one of the most popular horse breeds in the United States, known for its speed and agility.",
        "Horses have a unique digestive system that requires them to graze for most of the day.",
        "The Gypsy Vanner horse breed originated in the United Kingdom and is known for its colorful coat and luxurious mane and tail.",
        "Horses have a keen sense of hearing, which helps them detect approaching predators.",
        "The Belgian horse breed is one of the strongest draft horse breeds, capable of pulling heavy loads.",
        "Horses have a flight-or-fight response, meaning they will either flee from danger or confront it head-on.",
        "The Morgan horse breed is one of the earliest horse breeds developed in the United States, known for its versatility and endurance.",
        "Horses have been domesticated for thousands of years and have played a crucial role in human history.",
        "The Warmblood horse breed is a popular choice for sport horse disciplines due to its athleticism and temperament.",
        "Horses cannot burp or vomit. They have a very strong muscle ring called the cardiac sphincter at the entrance to their stomachs. This structure makes sure any food that enters the stomach cannot exit. Vomiting is a protection system; it rids the stomach of possible food-related intolerances, such as poisons, bacteria, and viral infections. It is thought then that this inability in horses to vomit has another purpose. When horses run, their intestines hammer on their stomach, causing pressure to build up. If their sphincter valve opened under pressure, horses would vomit every time they ran. In the wild, where horses are prey, if the horse vomited, eventually, the predator would catch its prey.",
        "Horses with pink skin can get a sunburn. Make sure to invest in protective sun gear for your horses on those blazing summer days.",
        "It takes 9-12 months to re-grow an entire horse hoof. Horse’s hooves normally grow at a rate of ¼ inch to ½ inch per month. However, this can vary throughout the year but are known to grow faster during the summer months.",
        "You can tell if a horse is cold by feeling behind their ears. If that area is cold, so is the horse. (Source: The Chronicle of the Horse)",
        "When horses look like they’re laughing, they’re engaging in a special nose-enhancing technique known as “flehmen”. The horse extends its neck, raises its head, and inhales as it rolls its upper lip back, displaying its front teeth. This activity helps determine whether a smell is good or bad (to the horse of course!).",
        "A horse's teeth take up more space in their head than their brain. ",
        "An adult horse’s brain weighs 22 oz.",
        "Horses can sleep both lying down and standing up. Horses have a unique survival adaptation called the stay apparatus that allows them to completely relax and sleep standing up. The point of this is to enable horses to run at the first sign of danger. However, they still need to lie down for short periods of time to achieve deep (REM) sleep and complete their sleep cycle. Horses can’t lie down for too long as that would put undue strain on their bones and internal organs.",
        "Horses in a herd (especially wild horses) will not lie down simultaneously. The reason is that because at least one will act as a look-out - or sentry - to alert its companions of potential dangers, thereby greatly increasing their chances for survival.",
        "Vocalizations are highly important to horses. Whinnying and neighing sounds are elicited when horses meet or leave each other. Stallions (adult male horses) perform loud roars as mating calls, and all horses will use snorts to alert others of potential danger.",
        "The first cloned horse was a Haflinger mare in Italy in 2003. Her name was Prometea",
        "Horses produce approximately 10 gallons of saliva a day. This is roughly 40 times the amount humans produce. To make this much saliva, horses use 5-10 gallons (22.7-40 liters) of water a day.",
        "Most of the time, wherever a horse's ear is pointing is where the horse is looking with the eye on the same side. If the ears are pointing in different directions, the horse is looking at two different things at the same time.",
        "Horses with typical anatomy are “obligate nasal breathers” which means they must breathe through their nostrils and cannot breathe through their mouths. The reason for this is the position of their epiglottis, which forms an airtight seal with the soft palate.",
        "Horses have a sense of humor. A fun horse fact is that horses are just that - funny! According to Dr. Sarah Ralston, VMD, PhD, DACVN, horses exhibit many “playful” behaviors throughout their life such as playing tag, mock fights, or nipping.",
        "Horses use their ears, eyes, and nostrils to express their mood. They also communicate their feelings through facial expressions. They can also understand human expressions and remember a person’s previous emotional state, adapting their behavior accordingly. This ability comes naturally to horses as they have complex facial expressions themselves.",
        "Most horses have 205 bones in their bodies, while humans have 206. While we both have a pelvis, only humans have collar bones. In humans, collar bones attach the arms to the skeleton and stabilize the shoulders. However, in horses this function is performed by the thoracic sling instead. The thoracic sling is a group of muscles, tendons, and ligaments that attach the forelimbs to the rest of the body. This is so they can run at a faster speed. Having a collarbone would restrict the horse’s reach and stride length, making them much slower runners. The horse and human skeletons are quite similar, even though we stand in completely different orientations. However, Arabian horses have one less pair of ribs, lumbar and tail vertebrae, meaning they only have 201 bones.",
        "Horses like sweet flavors and will usually reject anything sour or bitter. This is a really fun fact about horses, because it involves snacking! What's your horse's snack of choice?",
        "Most horses are born at night. You might think you’ve got time for a cup of coffee while you’re waiting for the birth, but you’d best keep an eye on the mother in labor. In the wild, a rapid night birth helps to protect a mare and foal from predators when they are at their most vulnerable.",
        "The fastest recorded sprinting speed of a horse was 88 kph (55 mph). This incredible speed was achieved in 2005 by a racing quarter horse called A Long Goodbye on a quarter-mile distance (0.40 km). The horse completed the race in exactly 20.686 seconds, running parts at over 50 mph. Most horses however gallop at around 44 kph or 27 mph.",
        "Newborn horses can stand, walk, and trot shortly after birth. Ideally, a foal should be up and nursing within two hours of birth. Horses can run within 24 hours after birth.",
        "The gestation period of a foal is two months longer than a human. It takes approximately 11 months for a foal to fully develop. Some foals can be a few weeks late or a few weeks early. Most breeders try to time foaling for early spring, so the foal can grow and exercise throughout the summer months.",
        "You can generally tell the difference between male and female horses by their number of teeth. Males have 40 while females have 36 (but honestly, most of us are going to use the much “easier” way). But they do not have any teeth in the middle of their mouths.",
        "Horses have very large eyes. In fact, they are among the largest eyes of all land-based mammals. In comparison to ours, horses’ eyes are eight times bigger! A horse’s eye is about 1.5 inches (4 cm) deep—essentially the width of a playing card. An injury affecting any part of its structure can create significant pain and severely affect the horse’s vision.",
        "Compared to other animals, horses have good vision. Humans with perfect vision are often described as having “20/20” vision. Horses are thought to be somewhere in the range of 20/30 to 20/60 – meaning that they can see from 20 feet away what an average human can see from 30-60 feet away. (By contrast, cats are thought to have 20/100 vision.)",
        "Because of the position of the horse’s eyes, they can see roughly 350 degrees around themselves. This is nearly four times our visual range! However, horses see the world very differently from us. They can only see 55 to 65 degrees with both eyes; the rest of their vision (190-230 degrees) is monocular. This means that their depth perception and ability to see details are quite poor. On the other hand, horses are exceptionally good at detecting motion, which is how they survived for millions of years. As soon as a predator came into their visual range, they were able to run instantly. But because they can’t make out moving shapes in their peripheral vision clearly, horses will spook at just about any sudden movement.",
        "Horses still hold a place of honor in many cultures, often linked to heroic exploits in war. China is one of those countries.",
        "A horse can see better at night than a human. However, a horse's eyes take longer to adjust from light to dark and from dark to light than a human.",
        "On the underside of a horse's hoof is a triangular shaped area called the “frog,\" which has multiple functions. It acts as a shock absorber for a horse's leg, absorbing the shock and distributing it to the internal digital cushion, a spongy structure under the horse’s heels. It also helps to pump venous blood back up the leg and is quite often called the horse’s “second heart”.",
        "The average horse's heart weighs approximately 9 or 10 pounds whereas a human heart weighs only 10-12 ounces (0.28-0.34 kg) on average. Racehorses have even bigger hearts, and heart size was the key to the success of many racing legends. For example, Secretariat’s heart weighed an astonishing 21 to 22 pounds (9.5-10 kg), while Phar Lap’s heart was 14 pounds (6.35 kg). Research has shown that a horse’s heart weighs around 1% of his body weight.",
        "Scientists believe that the first known ancestor of the horse lived about 50 million years ago. This prehistoric horse is called Eohippus and had four padded toes on the front legs and three padded toes on the back legs. ",
        "Horses have 16 muscles in each ear. This allows them to rotate their ears 180 degrees. ",
        "Horses remember a lot. You may have heard that elephants have an extremely superior memory. Did you know that horses are considered second in rank when it comes to memory in animals after elephants? Horses have great memories!",
        "At one time, people thought horses were colorblind. They’re not, though they are better at seeing yellows and greens than purples and violets.",
        "Horse hooves are made from the same protein – called keratin - that comprises human hair and fingernails. Because they’re constantly growing, it is very important that your horse’s hooves get a regular trim. This is especially important with young horses, as neglected hooves in young horses can result in crooked legs, and an uncertain future. ",
        "The most expensive horse ever sold* was Fusaichi Pegasus. He was purchased for a staggering $70 million in 2000 by Coolmore Stud in Ireland. This fee was paid in expectation that he would produce race-winning offspring and become a money-spinner in the horse breeding industry. (*This is still true in 2022). Unfortunately, this did not happen, although he did sire three Grade 1 stakes winners and was the grandsire of Belmont Stakes winner Ruler on Ice.",
        "The horse trailer (“horse box”) was invented by Lord George Bentinck, a U.K. man who needed a more effective transport for getting his prize horse “Elis” from one racetrack to another. He knew that if he made his horse walk the distances between racetracks, he would never be able to successfully win a race.",
        "In 1872, Leland Stanford (1824-1893) made a bet that at some point in the gallop, all four of a horse’s legs were off the ground at the same time. Eadweard Muybridge (1830-1904) proved him right by using a series of 24 cameras photographing a racehorse named Sallie Gardner.",
        "Horses are more secure and comfortable when traveling in a horse trailer if they can face the rear, but they prefer openings. Dr Natalie K. Waran at the University of Edinburgh studied the effects of transporting horses facing either forwards or backwards on their behaviour and heart rate, which was published in the Veterinary Record in 1996. “The most indicative finding is that the average heart-rate was significantly lower when horses travelled facing backwards,” says Michelle. “They move around less, vocalize less, and tend to hold their heads in a lower, more normal position. In this position, there is less pressure on the fragile head and chest.”",
        "A nineteenth-century horse named ‘Old Billy’ reportedly lived 62 years (1760-1822) in England. His exact breed is not known, although he was most likely a Shire-type horse with a brown coat and a white blaze. Curiously, his head was preserved and is currently on display at the Cecil Higgins Art Gallery and Bedford Museums.",
        "It is thought that the Przewalski horse is the only truly wild horse species still in existence. There are however numerous populations across the world of feral horses e.g., mustangs in North America, but these horses are descendants of domestic horses. All Przewalski’s horses today can be traced back to just 15 individuals captured from the wild a century ago. Named after the Russian explorer who discovered them in the nineteenth century, the breed was saved from extinction and recently reintroduced to their homeland in Mongolia.",
        "Approximately 4.6 million Americans work in the horse industry in one way or another. The total economic impact of the horse industry in the United States is $122 billion, creating 1.7 million jobs.",
        "There are approximately 58 to 60 million horses in the world. And, the vast majority are cared for by humans.",
        "There is only one species of domestic horse, but around 600 different breeds that specialize in everything from pulling wagons to racing. According to a 2017 genetic study, all modern horses descend from two ancient horse breeds: the Arabian and Turkoman horses. All horses are grazers.",
        "All existing horse breeds fit into five categories: hot-blooded, warm-blooded, cold-blooded/draft, pony, and miniature. Hot-blooded horses include the Arabian, Thoroughbred, and Barb breeds with origins in the Middle East. In contrast, cold-blooded (heavy) horses and ponies developed in northern Europe. A warm blood horse refers to any breed whose ancestors were crosses between hot-blooded and cold-blooded/pony type breeds. Finally, miniature horse breeds are scaled-down versions of their big cousins with a specified maximum height.",
        "Wild horses generally gather in groups of 3 to 20 animals. A stallion (mature male) leads the group, which consists of mares (females) and young foals. When young males become colts, at around two years of age, the stallion drives them away. The colts then roam with other young males until they can gather their own band of females.",
        "A horse’s height is measured in units known as \"hands.\" One hand is equal to four inches. The tallest horse on record was a Shire named Sampson. He was 21.2 hands (7 feet, 2 inches) tall. He was born in 1846 in Toddington Mills, England.",
        "The record for the longest jump over water is held by a horse named Something who jumped 27 feet, 6 and 3/4 inches on April 25, 1975, in Johannesburg, South Africa. He was ridden by Andre Ferreira.",
        "The record for the highest jump made by a horse is held by a horse named Huaso who jumped 8 feet, 1 and 1/4 inches on February 5th, 1949, in Vina del Mar, Chile. He was ridden by Captain Alberto Larraguibel.",
        "Horses drink at least 25 gallons of water a day on average. And, this number is even more in hotter climates!",
        "A zebroid is a cross between a zebra and any other member of the family Equidae (which, besides zebras, includes donkeys, ponies, and horses). A \"zonky\" is a cross between a zebra and a donkey. … A \"zony\" is a cross between a zebra and a pony. … A \"zorse\" is a cross between a zebra and a horse. You get the drift.",
        "If a horse has a red ribbon on its tail, it kicks. So... stay clear!",
        "Horses are social animals and will get lonely if kept alone. And, they will mourn the passing of a companion."
    };

    @JDASlashCommand(name = "fact", description = "Get a random horse fact")
    public void randomFact(GuildSlashEvent event) {
        int number = (int) (Math.random() * FACTS.length);
        event.reply("Horse Fact #" + number + ":\n" + FACTS[number]).queue();
    }
}
